### ISSUE TITLE
Calendar Questions

### ISSUE THREAD

**Issue by bexelbie** [OSAS/community-website#26]
1. Should our calendar offer an ics feed for people to subscribe too?
2. Should our calendar system be able to read an ics feed to autoload events like meetups or a community specific feed we want rolled up?

**Comment by duck-rh** [comment]
There is an ICS URL (https://community.redhat.com/events/all.ics), is this not sufficient to get all the events?
AFAIK it has been around for a very long time, but maybe not well advertised on the event page at the time.

We most certainly need to change the way we gather events, I would be in favor of such per-community feed and aggregation. It would be more flexible than the rh-events repo and would allow communities to delegate access with their own userbase (GL/GH org), I could not find a calendar aggregation plugin for WP. @jasonbrooks any idea?

If we can't find a plugin, then we may find a script doing the job and modify the current builder. Writing it is also an option but requires more time.

**Comment by bproffitt** [comment]
@duck-rh Actually, I just discovered that the link to the ICS calendar file is no longer working. Should I create a separate issue, or is this notice sufficient?

**Comment by jasonbrooks** [comment]
@bproffitt This is sufficient, we'll fix

**Comment by jasonbrooks** [comment]
@bproffitt the ics link is fixed now
