### ISSUE TITLE
Move official repo to GitHub

### ISSUE THREAD

**Issue by garrett** [OSAS/community-website#6]
- [x] Bugfix spree on internal GitLab issues
- [x] Mirror latest repo on GitHub
- [x] Port over WIP branches to GitHub
- [x] Enforce PR workflow with a locked master branch on GitHub
- [x] Set up CI
- [x] Change builder to use GitHub
- [x] Send email with instructions on switching
- [x] Lock down internal GitLab instance (to force people to switch)
- [x] Change description of this repo on GitHub

Please add more bullet points if I'm forgetting anything.

(This is a team effort between myself, @mscherer, & @duck-rh. @bproffitt is also looped in to help make sure this is a smooth transition.)

**Comment by garrett** [comment]
# Moving the RH Community site development to an external repository

## Make the switch in your own local checkouts

How to switch the default repo for pulls & pushes to GitHub:

```
git remote set-url origin git@github.com:OSAS/community-website.git
```

...this requires one has a GitHub account set up and has their ssh key associated with their account.

## Troubleshooting

If a `git pull` no longer works:

1. create a GitHub account (you can skip this is you already have an account)
2. add public SSH key at https://github.com/settings/keys
  - If you do not have an ssh key, run `ssh-keygen`
  - If you're not sure where your public ssh key is located, run `cat ~/.ssh/*.pub` to get its contents (if nothing shows up, you probably need to run `ssh-keygen` or you have a non-standard setup and should then know what you're doing anyway)

## New way to push

We've locked down the repo on GitHub so that nobody but admins can direcly push into master. Even if you have admin rights, pushing to master is frowned upon in most cases.

### Pull requests

The proper way to integrate new changes is to create a branch and send a pull request. Pull requests are then merged to master.

#### Squash merge PRs when possible

In most cases, you'll want to do a squash merge to make all commits into one commit and have that commit reference the pull request. (This is still useful when there's only one commit, as there will still be no special merge commit.)

#### Feature branch merges

If there are many isolated commits that deserve to be different commits (like merging in features, and the commits stand alone), please make each description useful and, ideally, not a single commit should break the build. In this case, do a normal branch merge (instead of a squash merge).

## Review PRs

Look over your own PRs to make sure they contain the correct commits and that the diff is doing what you expect.

Normally, it is not a good idea to rebase and/or force push a branch that's shared remote. If you're the only one with the branch checked out, and it is a branch used in a pull request, it's okay to do force update the branch, especially if it will be merged as a feature branch. If the PR is intended to be merged with a squash merge, however, it's fine to keep piling on the commits, as it will be expressed as one commit after the merge.

### Continuous Integration (CI)

In addition to humans reviewing PRs (yourself and others), we have enable continuous integration on pull requests. This means that a computer somewhere in "the cloud" will notice that the PR has been submitted and it will download the changes, apply the changes in the branch, and attempt to build the site.

If a CI build passes, that's great! If not, make changes and submit it again.

Please DO NOT merge pull requests (PRs) that do not pass continuous integration (CI) tests! Only merge branches that pass CI.

Following a strict CI policy ensures that we do not run into mysterious errors where someone made a typo and broke the build. It takes a lot of the guesswork out of the equation by solving mysteries before they even may occur.

**Comment by garrett** [comment]
## FAQ

### Why GitHub?

1. It's better to publish our code officially, instead of locking it up behind our VPN.
2. It enables the network effect where others can easily fix issues on the site.
3. It enables others to publish updates and send articles through a standardized process.
4. There's an in-browser contribution method that allows people to preview changes without having to build the site locally.
5. Continuous integration is supported (where all changes are automatically tested).
6. Other related sites are already hosted on GitHub, and this enables sharing updates across the sites a bit better.
7. The people most active on the site are already using GitHub to contribute to the similar sites, so this is a more consistent experience.

### What about GitLab.com?

GitLab.com, despite being built on GitLab CE, is a proprietary fork. That said, most of the codebase is similar to CE, and it does provide a migration path away from GitHub.com if we need this. In addition to moving the repo over (which can be done anywhere), it can also import issues.

### What about Pagure?

Pagure is great for code, but not nearly as good for editing documents in-browser. It doesn't allow for a nice contribution workflow like GitHub (or even GitLab).

**Comment by mscherer** [comment]
So, to change the CI, we just need to add a .travis.yml file. I did enable it on travis side, one can just copy the one from the other site. I will open a PR shortly.

**Comment by mscherer** [comment]
See https://github.com/OSAS/community-website/pull/7

**Comment by mscherer** [comment]
I switched the builder manually. Changing the url in ansible didn't switch anything.

**Comment by garrett** [comment]
@mscherer: So now https://community.redhat.com/ is built automatically when the master branch changes on GitHub?

**Comment by mscherer** [comment]
yep. same as before, just a different URL. Of course, the builder is still inside the firewall, and still can break, etc.

**Comment by garrett** [comment]
Hopefully the CI and forced PRs should help prevent a lot of the issues we've ran into with the Community site. :wink: (Basically most things except for the occasional random gem wonkiness.)

**Comment by mscherer** [comment]
The description of that repo should also be changed. Not sure if it must be done now, or once that's finish.

**Comment by garrett** [comment]
I've updated the README @ http://gitlab.osas.lab.eng.rdu2.redhat.com/garrett/community-middleman with instructions on how to switch to GitHub and made `master` a protected branch, so it should error out when someone tries to push to it.
