### ISSUE TITLE
 Multi-author bylines in Middleman

### ISSUE THREAD

**Issue by garrett** [OSAS/community-website#8]
From @jzb on our internal GitLab instance:

> There doesn't seem to be a way to add two or more authors to a post in Middleman. I have created a temporary workaround by just adding a new author with both names, but really this is sub-optimal b/c you can't just click the name and see all posts by one of the two (or more) authors.
> 
> This is something that comes up from time to time when we announce projects or posts that are worked on by multiple authors.

**Comment by garrett** [comment]
I looked that this a long while ago and was not sure how to solve it back then. Perhaps `middleman-blog` now has support or perhaps it's something we can patch in or work around? Would require someone to look into it further.

**Comment by duck-rh** [comment]
abandoned since the site moved to WP
